batch_size_0: 16
batch_size_1: 32
batches_report: 160
depth: 12
device: cpu
down_kernel_size: 15
learning_rate_0: 0.0001
learning_rate_1: 1.0e-05
num_filters: 24
output_path: out
output_size: 16384
sampling_rate: 22050
snippets_per_audio_file: 100
training_epochs: 70
training_path: ../../data/musdb18_wave
up_kernel_size: 5
validation_epochs_frequency: 1
validation_proportion: 0.1
